name: map_storytelling
channels:
  - defaults
dependencies:
- python>=3.8
- pip>=21
- scikit-image=0.18.1
- pip:
   - transformers~=4.10.2
   - ftfy
   - regex
   - tqdm
   - openai
   - gradio
   - scikit-learn
   - git+https://github.com/openai/CLIP.git
